services:
  db:
    image: mysql:5.7
    container_name: recfoodcato-db
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    expose:
      - "3306"
    networks:
      - recfoodcato-networks
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recfoodcato-api
    ports:
      - "8090:8080"
    volumes:
      - ./app/data:/app/app/data # Monta la carpeta data desde el host
    env_file:
      - ./.env
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 500s
    networks:
      - recfoodcato-networks

networks:
  recfoodcato-networks:
    driver: bridge
