services:
  db:
    image: mysql:5.7
    container_name: recfoodcato-db
    environment:
      MYSQL_DATABASE: "recfoodcato"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3308:3306"
    expose:
      - "3306"
    networks:
      - recfoodcato-networks
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recfoodcato-api
    ports:
      - "8090:8080"
    volumes:
    - ./app/data:/app/app/data  # Monta la carpeta data desde el host
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "12g"
    
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: admin
      DB_NAME: recfoodcato
      DB_PORT: 3306
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 500s
    networks:
      - recfoodcato-networks

networks:
  recfoodcato-networks:
    driver: bridge
